
services:
  golang:
    build:
      context: .
      dockerfile: golang.dockerfile
      # dockerfile: gcc.dockerfile
      args:
        WORKDIR: $WORKDIR
    image: mcpgen
    # container_name: $CONTAINER_NAME
    hostname: container-$COMPOSE_PROJECT_NAME
    volumes:
      - "./sources:/$WORKDIR/sources"
    tty: true
